// <auto-generated />
using System;
using CentroDeProduccion.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentroDeProduccion.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818212043_Fase2RecetasProduccion")]
    partial class Fase2RecetasProduccion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Ambito")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Ambito", "Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Insumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CantidadAcumuladaCompras")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("FactorConversion")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioPromedioPonderado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioUltimaCompra")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("ProveedorPrincipalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UnidadCompraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnidadConsumoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoSku")
                        .IsUnique();

                    b.HasIndex("ProveedorPrincipalId");

                    b.HasIndex("UnidadCompraId");

                    b.HasIndex("UnidadConsumoId");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.MovimientoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CantidadOriginal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DocumentoOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FactorConversionAplicado")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InsumoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("ProduccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductoTerminadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadOriginalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ProduccionId");

                    b.HasIndex("ProductoTerminadoId");

                    b.HasIndex("UnidadOriginalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosStock", t =>
                        {
                            t.HasCheckConstraint("CK_MovimientosStock_UnSoloTarget", "([InsumoId] IS NOT NULL AND [ProductoTerminadoId] IS NULL) OR ([InsumoId] IS NULL AND [ProductoTerminadoId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.PresentacionVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("PresentacionesVenta");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Produccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadProducida")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostoTotalInsumos")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponsableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Producciones");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.ProduccionSalida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ProduccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoTerminadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoSalida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProduccionId");

                    b.HasIndex("ProductoTerminadoId");

                    b.ToTable("ProduccionSalidas");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.ProductoTerminado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProduccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoSku")
                        .IsUnique();

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("ProductosTerminados");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CanalPedido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoriasProvee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionesPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HorarioAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontoMinimoCompra")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonaContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiempoEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CostoMetodo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MermaEstimada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rendimiento")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("TiempoProduccionEstimado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UnidadRendimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoSku")
                        .IsUnique();

                    b.HasIndex("UnidadRendimientoId");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.RecetaInsumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadNecesaria")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("InsumoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecetaOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnidadMedidaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("RecetaId");

                    b.HasIndex("RecetaOrigenId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("RecetaInsumos", t =>
                        {
                            t.HasCheckConstraint("CK_RecetaInsumos_UnSoloOrigen", "([InsumoId] IS NOT NULL AND [RecetaOrigenId] IS NULL) OR ([InsumoId] IS NULL AND [RecetaOrigenId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.RecetaVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CostoMetodo")
                        .HasColumnType("int");

                    b.Property<string>("DetallesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MermaEstimada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rendimiento")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId", "Version")
                        .IsUnique();

                    b.ToTable("RecetaVersiones");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRevocacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReemplazadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Revocado")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReemplazadoPorId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.UnidadMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Insumo", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Insumos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentroDeProduccion.Domain.Entities.Proveedor", "ProveedorPrincipal")
                        .WithMany("Insumos")
                        .HasForeignKey("ProveedorPrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CentroDeProduccion.Domain.Entities.UnidadMedida", "UnidadCompra")
                        .WithMany()
                        .HasForeignKey("UnidadCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentroDeProduccion.Domain.Entities.UnidadMedida", "UnidadConsumo")
                        .WithMany()
                        .HasForeignKey("UnidadConsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("ProveedorPrincipal");

                    b.Navigation("UnidadCompra");

                    b.Navigation("UnidadConsumo");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.MovimientoStock", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.Insumo", "Insumo")
                        .WithMany("Movimientos")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentroDeProduccion.Domain.Entities.Produccion", "Produccion")
                        .WithMany()
                        .HasForeignKey("ProduccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentroDeProduccion.Domain.Entities.ProductoTerminado", "ProductoTerminado")
                        .WithMany()
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentroDeProduccion.Domain.Entities.UnidadMedida", "UnidadOriginal")
                        .WithMany()
                        .HasForeignKey("UnidadOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentroDeProduccion.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Produccion");

                    b.Navigation("ProductoTerminado");

                    b.Navigation("UnidadOriginal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.PresentacionVenta", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.Receta", "Receta")
                        .WithMany("Presentaciones")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroDeProduccion.Domain.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receta");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Produccion", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.Receta", "Receta")
                        .WithMany()
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentroDeProduccion.Domain.Entities.Usuario", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receta");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.ProduccionSalida", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.Produccion", "Produccion")
                        .WithMany("Salidas")
                        .HasForeignKey("ProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroDeProduccion.Domain.Entities.ProductoTerminado", "ProductoTerminado")
                        .WithMany()
                        .HasForeignKey("ProductoTerminadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produccion");

                    b.Navigation("ProductoTerminado");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.ProductoTerminado", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentroDeProduccion.Domain.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Receta", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentroDeProduccion.Domain.Entities.UnidadMedida", "UnidadRendimiento")
                        .WithMany()
                        .HasForeignKey("UnidadRendimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UnidadRendimiento");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.RecetaInsumo", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentroDeProduccion.Domain.Entities.Receta", "Receta")
                        .WithMany("Insumos")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CentroDeProduccion.Domain.Entities.Receta", "RecetaOrigen")
                        .WithMany()
                        .HasForeignKey("RecetaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentroDeProduccion.Domain.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Receta");

                    b.Navigation("RecetaOrigen");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.RecetaVersion", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.Receta", "Receta")
                        .WithMany("Versiones")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CentroDeProduccion.Domain.Entities.RefreshToken", "ReemplazadoPor")
                        .WithMany()
                        .HasForeignKey("ReemplazadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CentroDeProduccion.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReemplazadoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Insumo", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Produccion", b =>
                {
                    b.Navigation("Salidas");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Proveedor", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Receta", b =>
                {
                    b.Navigation("Insumos");

                    b.Navigation("Presentaciones");

                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("CentroDeProduccion.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
